timeline_yaw_right:
  keyframes:
  - time: 0.00
    angle: 0.0
  - time: 0.44
    angle: 0.0
  - time: 0.47
    angle: 20.0
  - time: 0.50
    angle: 20.0
  - time: 0.53
    angle: -20.0
  - time: 0.94
    angle: -20.0
  - time: 0.97
    angle: -20.0
  - time: 1.00
    angle: 0.0
timeline_yaw_left:
  keyframes:
  - time: 0.00
    angle: -20.0
  - time: 0.03
    angle: 20.0
  - time: 0.47
    angle: 20.0
  - time: 0.50
    angle: 0.0
  - time: 0.94
    angle: 0.0
  - time: 0.97
    angle: -20.0
  - time: 1.00
    angle: -20.0
animation:
  duration: 15.5
ellipse:
  center_x: 0
  center_y: 40
  radius_x: 50
  radius_y: 10
