timeline_yaw_left:
  keyframes:
  - time: 0.0
    angle: 0.0
  - time: 1.0
    angle: 0.0
  - time: 0.5033333333333333
    angle: 24.266666666666666
timeline_yaw_right:
  keyframes:
  - time: 0.0
    angle: 20.0
  - time: 1.0
    angle: 20.0
  - time: 0.48833333333333334
    angle: -22.4
animation:
  duration: 8.0
ellipse:
  center_x: 0
  center_y: 40
  radius_x: 76
  radius_y: 40
