timeline_yaw_left:
  keyframes:
  - time: 0.0
    angle: 0.0
  - time: 0.5
    angle: 15.0
  - time: 1.0
    angle: 0.0
  - time: 0.76
    angle: -0.4000000000000057
timeline_yaw_right:
  keyframes:
  - time: 0.0
    angle: 20.0
  - time: 0.24333333333333335
    angle: 44.0
  - time: 1.0
    angle: 20.0
  - time: 0.93
    angle: 30.39999999999999
animation:
  duration: 4.0
ellipse:
  center_x: 0
  center_y: 40
  radius_x: 75
  radius_y: 20
