timeline_yaw_left:
  keyframes:
  - time: 0.0016666666666666668
    angle: -0.16666666666666785
  - time: 0.03333333333333333
    angle: 15.333333333333329
  - time: 0.47333333333333333
    angle: 15.333333333333329
  - time: 0.9566666666666667
    angle: -14.833333333333334
  - time: 0.535
    angle: -15.0
  - time: 0.9966666666666667
    angle: 0.1666666666666643
timeline_yaw_right:
  keyframes:
  - time: 0.0
    angle: 0.0
  - time: 0.47333333333333333
    angle: 15.333333333333329
  - time: 0.5366666666666666
    angle: -14.833333333333334
  - time: 1.0
    angle: 0.0
  - time: 0.03166666666666667
    angle: 15.166666666666664
  - time: 0.9566666666666667
    angle: -14.833333333333334
animation:
  duration: 8.0
ellipse:
  center_x: 0
  center_y: 40
  radius_x: 75
  radius_y: 5
